### PR TITLE
Persistence does not use stored procedures

### LINKED ISSUE #35: Request charge and stored procedures
As part of our scaling efforts we are looking at our CosmosDB utilization and costs.  We noticed the procedure calling JSON.parse and wanted to see if we could send the extracted values (graintype, id and etag) as parameters instead of parsing it, and how this would affect the request charge (RC). Short version it doesn't.

 We did however find the RU cost somewhat high compared to calling Cosmos operations directly. Based on the document below[1], here's our findings

Average RC read using stored procedure: 5.63
Average RC create using stored procedure: 11.68
Average RC update using stored procedure: 14.89

RC read using GET:  1
RC create using PUT:  6.29
RC update using POST: 10.29

This seems rather excessive, and we're wondering if one can improve the stored procedures or skip it and call Cosmos db directly.

```
{
  "id": "b780de47-a7d2-44c5-8a8f-7eea29e9561f__GrainReference=4f3d549833293c5e5d419486ec1f04a30600000031c1478e+7054fbd0-9dce-48ed-ab5c-4ed85ba0c66c",
  "GrainType": "Ps.Personlig.Grains.FavorittGrainRadio",
  "State": {
    "State": {
      "Case": "V1",
      "Fields": [
        {
          "FavoriserbarId": "K|saann_er_du",
          "Medium": "radio",
          "KildeType": "manuell",
          "Registrert": 15481904238110000,
          "Slettet": {
            "Case": "Some",
            "Fields": [
              15518746264096320
            ]
          }
        }
      ]
    }
  },
  "PartitionKey": "testh"
}
```

### PR DESCRIPTION
**Pull request by Ulriksen**
Call CosmosDB directly, reduce complexity and request charge. 

Fixes #35.

### CODE REVIEW

**Comment by galvesribeiro** [comment]
Looks good @Ulriksen 

May I ask you why the lookup was left as an sproc?

**Comment by Ulriksen** [comment]
I am really not sure about the indexing part, there's a few problems with the current implementation vs partitions in CosmosDB. See https://github.com/dotnet/orleans/issues/5432. 

A benefit of moving indexing from sproc to query is the support for cross partition searches, thus supporting  custom partitioning schemes.

**Comment by Ulriksen** [comment]
Got a conflict exception we've not seen before. Looking into it.

**Comment by Ulriksen** [comment]
Resolved the exceptions problems. Etag was not set when reading state after it had been cleared.

**Comment by Ulriksen** [comment]
Before and after 
image

**Pull request merged**
